#include "screen_ui.h"
#include "screen_font.h"
#include <string.h>
#include <stdio.h>
#include "vendor/qrcodegen.h"

screen_recording_timer_t screen_ui_recording_timer(uint32_t start_ms,
                                                   uint32_t now_ms,
                                                   uint32_t limit_seconds) {
  screen_recording_timer_t timer = {0};
  const uint32_t elapsed_ms = now_ms - start_ms;
  const uint64_t limit_ms = (uint64_t)limit_seconds * 1000u;
  const uint64_t remaining_ms = elapsed_ms >= limit_ms ? 0 : limit_ms - elapsed_ms;
  const uint32_t seconds = (uint32_t)((remaining_ms + 999u) / 1000u);
  const uint32_t display_seconds = seconds > 5999u ? 5999u : seconds;
  snprintf(timer.text, sizeof(timer.text), "%02lu:%02lu",
           (unsigned long)(display_seconds / 60u),
           (unsigned long)(display_seconds % 60u));
  timer.warning = remaining_ms <= 5000u ? SCREEN_RECORDING_FIVE_SECONDS :
                  remaining_ms <= 10000u ? SCREEN_RECORDING_TEN_SECONDS :
                  SCREEN_RECORDING_NORMAL;
  return timer;
}

screen_ui_view_t screen_ui_view_with_phase(state_t state,
                                           screen_processing_phase_t phase) {
  switch (state) {
    case STATE_RECORDING:
      return (screen_ui_view_t){"СЛУШАЮ", "ОТПУСТИТЕ\nДЛЯ ОТПРАВКИ", 0xF50A, SCREEN_ICON_LISTENING};
    case STATE_PROCESSING:
      if (phase == SCREEN_PROCESSING_TRANSCRIBING)
        return (screen_ui_view_t){"СЛЫШУ", "РАСПОЗНАЮ РЕЧЬ", 0xF5A8, SCREEN_ICON_THINKING};
      if (phase == SCREEN_PROCESSING_SYNTHESIZING)
        return (screen_ui_view_t){"ГОТОВЛЮ", "ОТВЕТ", 0xF5A8, SCREEN_ICON_THINKING};
      return (screen_ui_view_t){"ДУМАЮ", "ОБРАБАТЫВАЮ", 0xF5A8, SCREEN_ICON_THINKING};
    case STATE_PLAYING:
      return (screen_ui_view_t){"ОТВЕЧАЮ", "ЗАЖМИТЕ ДЛЯ\nСТОПА", 0x38B8, SCREEN_ICON_SPEAKING};
    case STATE_ERROR:
      return (screen_ui_view_t){"ОШИБКА", "НАЖМИТЕ ДЛЯ\nСБРОСА", 0xF50A, SCREEN_ICON_ERROR};
    case STATE_BOOT:
      return (screen_ui_view_t){"ЗАПУСК", "ПОДКЛЮЧАЮСЬ", 0x74BF, SCREEN_ICON_IDLE};
    case STATE_IDLE:
    default:
      return (screen_ui_view_t){"ГОТОВА", "НАЖМИТЕ ДЛЯ\nСТАРТА", 0x74BF, SCREEN_ICON_IDLE};
  }
}

screen_ui_view_t screen_ui_view(state_t state) {
  return screen_ui_view_with_phase(state, SCREEN_PROCESSING_THINKING);
}


screen_ui_view_t screen_ui_view_with_network(state_t state, screen_processing_phase_t phase,
                                             bool wifi_connected, bool vpn_ready) {
  if (state == STATE_IDLE) {
    if (!wifi_connected)
      return (screen_ui_view_t){"СЕТЬ", "ОЖИДАЮ WI-FI", 0xF5A8, SCREEN_ICON_THINKING};
    if (!vpn_ready)
      return (screen_ui_view_t){"VPN", "ОЖИДАЮ VPN", 0xF5A8, SCREEN_ICON_THINKING};
  }
  return screen_ui_view_with_phase(state, phase);
}


// Fixed version 3: 29 modules plus a four-module quiet zone, at 3 px/module.
// Cache encoding because the status screen refreshes every 180 ms.
bool screen_ui_draw_setup(uint16_t *pixels, int width, int height, const char *ssid) {
  static char cached_ssid[33];
  static uint8_t qr[qrcodegen_BUFFER_LEN_FOR_VERSION(3)];
  if (!pixels || width < 135 || height < 240 || !ssid || !*ssid || strlen(ssid) > 32)
    return false;
  if (strcmp(cached_ssid, ssid) != 0) {
    // AP names are generated by the board, never supplied by the user.
    if (strpbrk(ssid, "\\;,:\"")) return false;
    char payload[64];
    snprintf(payload, sizeof(payload), "WIFI:T:nopass;S:%s;;", ssid);
    uint8_t scratch[qrcodegen_BUFFER_LEN_FOR_VERSION(3)];
    if (!qrcodegen_encodeText(payload, scratch, qr, qrcodegen_Ecc_MEDIUM,
                             3, 3, qrcodegen_Mask_AUTO, true)) return false;
    strcpy(cached_ssid, ssid);
  }
  int left = (width - 111) / 2;
  for (int y = 0; y < 111; ++y)
    for (int x = 0; x < 111; ++x)
      pixels[(75 + y) * width + left + x] =
          qrcodegen_getModule(qr, x / 3 - 4, y / 3 - 4) ? 0x0000 : 0xffff;
  const struct {
    const char *text;
    int y;
    screen_font_size_t font;
    uint16_t color;
  } lines[] = {
    {"НАСТРОЙКА", 39, SCREEN_FONT_HINT, 0xF5A8},
    {"ТОЧКА ДОСТУПА", 57, SCREEN_FONT_SMALL, 0xEF9F},
    {"192.168.4.1", 195, SCREEN_FONT_HINT, 0xEF9F},
  };
  for (unsigned i = 0; i < sizeof(lines) / sizeof(lines[0]); ++i) {
    int measured = screen_font_measure(lines[i].font, lines[i].text);
    if (measured < 0 || measured > width - 20 ||
        !screen_font_draw_centered(pixels, width, height, width / 2, lines[i].y,
                                   lines[i].font, lines[i].text, lines[i].color))
      return false;
  }
  return true;
}
